name: lsst-tests

on:
  push:
    branches:
      - master
  pull_request: null

env:
  PY_COLORS: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lsst-tests:
    name: lsst-tests
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ngmix: ["ngmix-upstream", "ngmix-released"]

    steps:
      - name: free disk space for stackvana
        uses: endersonmenezes/free-disk-space@v3
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          rm_cmd: "rmz"  # Faster cleanup

      - uses: actions/checkout@v6

      - uses: mamba-org/setup-micromamba@v2.0.7
        with:
          environment-name: test
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
            show_channel_urls: true
            always_yes: true
          create-args: >-
            stackvana=0
            lsstdesc-weaklensingdeblending
            lsstdesc-wl-shear-sims
            pip

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          micromamba install --yes --file requirements.txt
          micromamba install --yes --file dev-requirements.txt

          if [[ "${{ matrix.ngmix }}" == "ngmix-upstream" ]]; then
            micromamba uninstall ngmix --force
            pip install --no-deps --no-build-isolation git+https://github.com/esheldon/ngmix.git
          fi

          pip install --no-deps --no-build-isolation git+https://github.com/LSSTDESC/descwl_coadd.git
          pip install --no-deps --no-build-isolation  -e .

      - name: metadetect test suite, including lsst
        shell: bash -l {0}
        run: |
          # we need to unsetup the metadetect that comes with the stack
          unsetup -j metadetect
          pytest -v -n 4 --cov=metadetect --cov-report term-missing metadetect 
